#page title
page_title                                : Sathorn                                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1447295899                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://sathorn.app/assets/sathorn-presskit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Sathorn                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : $4.99                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Apple Music to your ears

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Stephen Bodnar                               
your_link                                 : https://vaporforums.io/about                    
your_city                                 : Bangkok                                
email_address                             : stephen@sathorn.app
facebook_username                         :                                           
instagram_username                        : j0eybodnar2
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Instagram Share
    description                           : Share song, playlist, album, and radio artwork from Apple Music to your Instagram Story
    fontawesome_icon_name                 : magic
    
  - title                                 : Album Folders
    description                           : Organize your albums into folders
    fontawesome_icon_name                 : mobile

  - title                                 : Light, Dark, and True Black
    description                           : Sathorn supports multiple themes, as well as any custom tint color
    fontawesome_icon_name                 : play-circle

  - title                                 : Browse User Generated Playlists
    description                           : Browse playlists generated by your friends and other Apple Music members
    fontawesome_icon_name                 : sync

  - title                                 : Extensive Today Widget
    description                           : Control playback, add songs to your library, play stations and playlists--all from your lock screen
    fontawesome_icon_name                 : adjust
  
  - title                                 : Favorites List
    description                           : Pin your favorite songs, playlists, and albums to the top of their respective lists for quick and easy access
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
